### ISSUE TITLE
朋友圈管理点击用户名筛选按钮会出错

### ISSUE THREAD

**Issue by sion934** [xuchengsheng/wx-dump-4j#12]
错误提示：Something went wrong.
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btext%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by caiyouzai** [comment]
我也遇到了相同的问题

**Comment by xuyuan0808** [comment]
俺也一样   Something went wrong.  Objects are not valid as a React child (found: object with keys {text}). If you meant to render a collection of children, use an array instead.

**Comment by xuchengsheng** [comment]
能贴出详细的堆栈信息吗
