### ISSUE TITLE
所有的视频文件都是文件已过期或已被清理

### ISSUE THREAD

**Issue by xuyuan0808** [xuchengsheng/wx-dump-4j#13]
会话和朋友圈内的视频相关文件都是已过期或已被清理，无法正常展示。
![image](https://github.com/xuchengsheng/wx-dump-4j/assets/164338556/247b7399-a79b-4a07-9cf6-97bd71f3685d)

**Comment by xuchengsheng** [comment]
目前暂时还不知道视频相关的内容，因为没有找到匹配到视频与数据库内容之间的关系。
