### ISSUE TITLE
数据同步成功，但是UI 上没有数据

### ISSUE THREAD

**Issue by geekyouth** [xuchengsheng/wx-dump-4j#15]
![image](https://github.com/xuchengsheng/wx-dump-4j/assets/12899262/c82fdda5-46de-4934-9422-a918d2037d02)
![image](https://github.com/xuchengsheng/wx-dump-4j/assets/12899262/8db283e9-1ad8-4c07-bbde-01f3c3884aa0)

![image](https://github.com/xuchengsheng/wx-dump-4j/assets/12899262/41dd30f6-dc56-437e-9a34-45ec6167fdd7)

**Comment by xuchengsheng** [comment]
请升级到最新版本
