### ISSUE TITLE
群组聊天消息导出失败

### ISSUE THREAD

**Issue by 24kb-star** [xuchengsheng/wx-dump-4j#18]
![image](https://github.com/xuchengsheng/wx-dump-4j/assets/42843925/80083cc2-dc2d-4ce9-a6b8-6642f999d703)
如图，是因为群组的名称导致创建文件失败了吗。附上群组名称如下
![image](https://github.com/xuchengsheng/wx-dump-4j/assets/42843925/bb6e7db4-c664-4ec2-a745-e8cc906557c5)
感谢作者解答！

**Comment by xuchengsheng** [comment]
已解决
