### ISSUE TITLE
会话显示错乱

### ISSUE THREAD

**Issue by hqxyhc** [xuchengsheng/wx-dump-4j#2]
微信管理-会话管理： 点一个会话 还没等响应完成 就去点别的会话就显示错乱了
如下图，游戏群的聊天记录显示到源码群啦
![5cb3e151a87593f748abd10d623efce](https://github.com/xuchengsheng/wx-dump-4j/assets/45394967/fb32756b-9b9a-4e28-bb58-985f14611407)

**Comment by xuchengsheng** [comment]
已解决
