### ISSUE TITLE
微信修改了文件目录，无法找到并解密文件

### ISSUE THREAD

**Issue by yeqingyun** [xuchengsheng/wx-dump-4j#31]
![image](https://github.com/xuchengsheng/wx-dump-4j/assets/16248389/35d92135-d5c1-4103-9a43-51f4b525b21b)

**Comment by xuchengsheng** [comment]
你能加我微信给一些更多的信息吗

**Comment by xuchengsheng** [comment]
微信号：spring-reading

**Comment by yeqingyun** [comment]
这个微信号搜不到用户

**Comment by yeqingyun** [comment]
> 微信号：spring-reading

微信搜不到

**Comment by xuchengsheng** [comment]
已解决

**Comment by xuchengsheng** [comment]
已经解决了
